graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 402
         y 80
      ]
   ]
   node [
      id 1
      graphics [
         x 465
         y 78
      ]
   ]
   node [
      id 2
      graphics [
         x 524
         y 81
      ]
   ]
   node [
      id 3
      graphics [
         x 583
         y 78
      ]
   ]
   node [
      id 4
      graphics [
         x 645
         y 78
      ]
   ]
   node [
      id 5
      graphics [
         x 689
         y 78
      ]
   ]
   node [
      id 6
      graphics [
         x 340
         y 162
      ]
   ]
   node [
      id 7
      graphics [
         x 396
         y 162
      ]
   ]
   node [
      id 8
      graphics [
         x 451
         y 162
      ]
   ]
   node [
      id 9
      graphics [
         x 495
         y 164
      ]
   ]
   node [
      id 10
      graphics [
         x 536
         y 164
      ]
   ]
   node [
      id 11
      graphics [
         x 587
         y 164
      ]
   ]
   node [
      id 12
      graphics [
         x 414
         y 242
      ]
   ]
   node [
      id 13
      graphics [
         x 499
         y 242
      ]
   ]
   node [
      id 14
      graphics [
         x 588
         y 244
      ]
   ]
   node [
      id 15
      graphics [
         x 527
         y 325
      ]
   ]
   node [
      id 16
      graphics [
         x 77
         y 169
      ]
   ]
   node [
      id 17
      graphics [
         x 110
         y 169
      ]
   ]
   node [
      id 18
      graphics [
         x 140
         y 169
      ]
   ]
   node [
      id 19
      graphics [
         x 176
         y 169
      ]
   ]
   node [
      id 20
      graphics [
         x 206
         y 169
      ]
   ]
   node [
      id 21
      graphics [
         x 236
         y 169
      ]
   ]
   node [
      id 22
      graphics [
         x 123
         y 223
      ]
   ]
   node [
      id 23
      graphics [
         x 197
         y 228
      ]
   ]
   node [
      id 24
      graphics [
         x 57
         y 231
      ]
   ]
   node [
      id 25
      graphics [
         x 185
         y 312
      ]
   ]
   node [
      id 26
      graphics [
         x 356
         y 394
      ]
   ]
   node [
      id 31
      graphics [
         x 495
         y 164
      ]
   ]
   edge [
      source 5
      target 11
   ]
   edge [
      source 4
      target 11
   ]
   edge [
      source 3
      target 11
   ]
   edge [
      source 2
      target 10
   ]
   edge [
      source 1
      target 10
   ]
   edge [
      source 0
      target 10
   ]
   edge [
      source 10
      target 14
   ]
   edge [
      source 11
      target 14
   ]
   edge [
      source 14
      target 15
   ]
   edge [
      source 15
      target 26
   ]
   edge [
      source 13
      target 15
   ]
   edge [
      source 12
      target 15
   ]
   edge [
      source 25
      target 26
   ]
   edge [
      source 23
      target 25
   ]
   edge [
      source 22
      target 25
   ]
   edge [
      source 24
      target 25
   ]
   edge [
      source 9
      target 14
   ]
   edge [
      source 8
      target 13
   ]
   edge [
      source 7
      target 13
   ]
   edge [
      source 6
      target 13
   ]
   edge [
      source 21
      target 23
   ]
   edge [
      source 20
      target 23
   ]
   edge [
      source 19
      target 23
   ]
   edge [
      source 18
      target 22
   ]
   edge [
      source 17
      target 22
   ]
   edge [
      source 16
      target 22
   ]
]