graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 114
         y 76
      ]
   ]
   node [
      id 1
      graphics [
         x 246
         y 138
      ]
   ]
   node [
      id 2
      graphics [
         x 314
         y 61
      ]
   ]
   node [
      id 3
      graphics [
         x 124
         y 167
      ]
   ]
   node [
      id 8
      graphics [
         x 299
         y 223
      ]
   ]
   node [
      id 9
      graphics [
         x 393
         y 116
      ]
   ]
   node [
      id 10
      graphics [
         x 415
         y 53
      ]
   ]
   node [
      id 15
      graphics [
         x 488
         y 296
      ]
   ]
   node [
      id 16
      graphics [
         x 553
         y 161
      ]
   ]
   node [
      id 17
      graphics [
         x 405
         y 239
      ]
   ]
   node [
      id 18
      graphics [
         x 329
         y 318
      ]
   ]
   node [
      id 19
      graphics [
         x 209
         y 262
      ]
   ]
   node [
      id 20
      graphics [
         x 221
         y 197
      ]
   ]
   node [
      id 22
      graphics [
         x 454
         y 217
      ]
   ]
   edge [
      source 1
      target 3
   ]
   edge [
      source 3
      target 0
   ]
   edge [
      source 0
      target 2
   ]
   edge [
      source 2
      target 1
   ]
   edge [
      source 10
      target 2
   ]
   edge [
      source 2
      target 9
   ]
   edge [
      source 9
      target 8
   ]
   edge [
      source 8
      target 1
   ]
   edge [
      source 22
      target 9
   ]
   edge [
      source 22
      target 17
   ]
   edge [
      source 8
      target 17
   ]
   edge [
      source 17
      target 9
   ]
   edge [
      source 9
      target 16
   ]
   edge [
      source 16
      target 15
   ]
   edge [
      source 15
      target 22
   ]
   edge [
      source 22
      target 18
   ]
   edge [
      source 18
      target 8
   ]
   edge [
      source 8
      target 19
   ]
   edge [
      source 20
      target 19
   ]
   edge [
      source 20
      target 3
   ]
   edge [
      source 20
      target 1
   ]
   edge [
      source 22
      target 16
   ]
]